Import types instead of import and prepare update to TS5.0
langium/langium pull request #1018
Opened 2023-04-11 13:20 UTC by gfontorbe

Closes #960 

* Prepare upgrade to TypeScript 5.0.x
* Adds new linter rule to use `import type` instead of `import` for imports that are only used for types and not values
* Fixed linter issues for the new rule
* Adapted langium-cli and generators to reflect those changes
* Some styling here and there

2023-04-11 13:47 UTC, dhuebner requested changes
Please remove the test project from the package-lock. Also check that clean-up step is inside a `finally` block

2023-04-11 13:47 UTC, dhuebner commented on package-lock.json
> +    "examples/hello-world": {
This should not happen. Failed the CLI test, or is the clean-up after test disabled? 
Afaik I set it up to clean up even on test failure.

2023-04-11 13:58 UTC, gfontorbe commented
> Please remove the test project from the package-lock. Also check that clean-up step is inside a `finally` block

The clean-up step is already in a finally block, not sure why this was added to the package-lock...

2023-04-11 14:03 UTC, dhuebner commented
> > Please remove the test project from the package-lock. Also check that clean-up step is inside a `finally` block
> 
> The clean-up step is already in a finally block, not sure why this was added to the package-lock...

Do you have this folder locally? Maybe it is there since you was adding new CLI tests?

2023-04-11 14:06 UTC, dhuebner approved these changes

2023-04-11 14:08 UTC, dhuebner commented
@gfontorbe 
It is really difficult to track all the changes.
Just hope we have enough tests and enough time to find potential bugs :) 
Would be nice if someone else could also look through.

2023-04-12 14:41 UTC, msujew requested changes
It isn't noticeable since the `ast.ts` files get generated with an `eslint-disable` instruction, but these files aren't using the `import type` statements correctly:

```ts
import type { AstNode, Reference, ReferenceInfo, TypeMetaData } from 'langium';
import { AbstractAstReflection } from 'langium';
```

We currently only generate
```ts
import { AstNode, AbstractAstReflection, Reference, ReferenceInfo, TypeMetaData } from 'langium';
```

2023-05-03 14:10 UTC, msujew approved these changes
Looks good, please rebase on top of the latest `main` and merge at the end of the week as discussed 👍

2023-05-04 08:58 UTC, merged