Automate release process
langium/langium pull request #1031
Opened 2023-04-20 15:02 UTC by msujew

Simplifies and mostly automates the release process:

1. Updating tags only requires two commands to run know.
2. Publishing will be performed from within GitHub actions.

Since the `npm version` script does not automatically update dependency versions between the packages, we need to update them via a script. This is what `version:dependencies` does.

2023-04-20 15:44 UTC, kaisalmen reviewed
Nice work. Tested it locally. After performing the suggested changes it looks good.

2023-04-20 15:44 UTC, kaisalmen commented on CONTRIBUTING.md
> +    * Run `npm run version:dependencies`
langium-vscode does not have the "~" at the langium version and therefore the script does not work there.

2023-04-20 15:44 UTC, kaisalmen commented on scripts/update-version.js
> +        replaceAll('langium-cli', true, version),
You have to add `langium` here as well otherwise the `langium-cli` devDependency is unchanged and then polluting the lock file with old versions.

2023-04-21 11:36 UTC, kaisalmen approved these changes
Looks good. LGTM 🎉

2023-04-22 21:05 UTC, spoenemann requested changes
Please add the `--provenance` flag to make use of the new supply chain security badge:

https://github.blog/2023-04-19-introducing-npm-package-provenance/

2023-04-22 21:05 UTC, spoenemann commented on .github/workflows/publish.yml
> +        OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
These variables seem unused.

2023-04-23 17:49 UTC, spoenemann approved these changes
Great improvement, thank you!

2023-05-02 12:46 UTC, merged