Make validation checks less strict
langium/langium pull request #942
Opened 2023-02-17 11:50 UTC by msujew

Closes https://github.com/langium/langium/issues/941

2023-02-17 11:58 UTC, sailingKieler requested changes
Great, thanks @msujew for the prompt reaction.

However, 2 wishes:
 * add a bit of prose to the definition of `AstTypeList` & `ValiditionChecks` on what it is supposed to describe/denote (daniel and me tried to guess it yesterday)
 * create at least a related unit test

2023-02-17 12:12 UTC, msujew commented
We don't really have a testing infrastructure in place for type testing. Since this is a type change (it doesn't actually change any runtime code), there's little need for runtime tests.

2023-02-27 11:05 UTC, spoenemann reviewed
I don't see #958 fixed, the invalid switch case in `computeIsSubtype` is still generated.

2023-02-27 11:05 UTC, spoenemann commented on packages/langium/src/grammar/type-system/types-util.ts
> +        return type.types.some(hasAstType);
Should we better use `every`? A union that combines AST types with primitives is not usable as AST type.

2023-03-03 14:08 UTC, sailingKieler approved these changes
I basically agree, although I would love to see some comments here and there simplifying to understand what's going on and what aim of the particular filter criteria is (e.g. `hasAstType(e.type)`)

Provided a few suggestions for improving the documentation

2023-03-10 10:49 UTC, spoenemann commented
AFAICT https://github.com/langium/langium/pull/942#pullrequestreview-1315362762 is still valid.

2023-03-10 11:05 UTC, msujew commented
@spoenemann Indeed, I pushed a fix for that. Thanks 👍

2023-03-10 11:10 UTC, spoenemann approved these changes
:+1:

2023-03-10 11:35 UTC, merged